package com.ExceptionHandling_task_4__21_8_2024;

public class Example3 {
    public static void main(String[] args) {
        try {

        } catch (ArithmeticException e) {

        } catch (ArithmeticException e) // unreachable code because arithmeticException catch 1st catch block

        {

        }
    }
}
